@CodeConnect.WebAPI_HostAddress = https://localhost:7124

POST {{CodeConnect.WebAPI_HostAddress}}/api/user/getuserdetails
Accept: application/json
Content-Type: application/json
Authorization: bearer 

"MatK"
###
