name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build WebAssembly
      run: |
        cd CodeConnect.WebAssembly
        dotnet build --no-restore

    - name: Build Web API
      run: |
        cd CodeConnect.WebAPI
        dotnet build --no-restore
        
    - name: Build Class Libraries
      run: |
        cd ApplicationLayer
        dotnet build --no-restore

        cd DomainLayer
        dotnet build --no-restore

        cd InfrastructureLayer
        dotnet build --no-restore

    - name: Build and Test Test Project
      run: |
        cd TestLayer
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
